##Diferencias entre np.array y np.matrix

La principal diferencia entre los los arreglos y las matrices radica en que las matrices son especificamente de 2 dimensiones, mientras que los arreglos son N-dimensiones.


Las matrices proveen una notación conveniente para la multiplicación de matrices dado por a*b, mientras que al utilizar la misma notación con arreglos se obtiene una multiplicación elemento por elemento.

Ejemplo:

In [1]:
import numpy as np

a = np.mat('4 3; 2 1')
b = np.mat('1 2; 3 4')
print(a*b)

c = np.array([[4, 3], [2, 1]])
d = np.array([[1, 2], [3, 4]])

print(c*d)

[[13 20]
 [ 5  8]]
[[4 6]
 [6 4]]


Adicionalmente al revisar la documentación de numpy para np.matrix se observa lo siguiente:

***It is no longer recommended to use this class, even for linear algebra. Instead use regular arrays. The class may be removed in the future.***

Que indica que en el futuro esta clase será removida y es recomendable utilizar arreglos.

**Ejemplo en DS** : en inteligencia artificial y ML en la sub-rama "reinforcement learning" la "ecuacion de bellman" puede aplicarse de manera vectorizada a traves del operar vectores, matrices y escalares en una sola expresión.

<img src="https://rebornhugo.github.io/assets/images/post_images/%E5%BC%BA%E5%8C%96%E5%AD%A6%E4%B9%A02/bellman%20equation2.PNG">

* n = número de estados del sistema.
* V(s) = vector que representa el valor esperado para cierto estado
* R = recompensa inmediata percibida por el agente al salir de cierto estado.(vector)
* P = matriz de transicion de la cadena de Markov sub-yacente.(matriz)
* γ = factor de descuento de recompensas futuras(escalar)

Calcular V(s) para el siguiente sistema aplicando la ecuación de bellman de manera vectorizada.

In [ ]:
V = np.array([0,0,0]) # valor inicial de V(s)
R = np.array([10,2,5]) # vector de recompensas
P = np.array([[0.5,0.25,0.25],
              [0.2,0.40,0.40],
              [0.80,0.10,0.10]])  # matriz de transición
gamma = 0.99
vs = R + gamma*np.matmul(V,P)
print(vs)


### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [22]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

def relu(x):
    condiciones = [x<0,x>0]
    resultados =  [0,x]
    return np.select(condiciones,resultados)

def neural_network(x):
  hl = [[0.712, 0.355, 0.268], [0.112, 0.855, 0.468]]
  ol = [0.116, 0.329, 0.708]

  hl_w = np.matmul(x,hl)
  hl_w = sigmoid(hl_w)
  hl_w = relu(hl_w)
  print(hl_w)
  ol_w = np.matmul(hl_w, ol)
  ol_w = relu(ol_w)
  return ol_w

x = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])
print(neural_network(x))


[[0.5732687  0.85138432 0.72368206]
 [0.56561932 0.62040086 0.57224093]
 [0.98972791 0.99992287 0.9961353 ]
 [0.99990057 0.99991645 0.99758587]
 [0.99610438 0.99884211 0.98545706]
 [0.5752246  0.68793868 0.61177987]
 [0.99988879 0.99980357 0.99615067]
 [1.         1.         1.        ]
 [0.997213   0.99991084 0.99638845]
 [1.         1.         1.        ]]
[0.85897151 0.6748703  1.14904686 1.15125178 1.14187076 0.72619803
 1.15019715 1.153      1.1500904  1.153     ]
